# Generated by Django 4.0.4 on 2022-05-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('dni', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
