# Generated by Django 4.0.4 on 2022-05-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='dni',
            field=models.IntegerField(unique=True),
        ),
    ]
