# Generated by Django 4.0.4 on 2022-05-25 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_alter_registro_dni'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Familia',
        ),
    ]
